apiVersion: v1
kind: Service
metadata:
  name: smart-parking-backend
  namespace: smart-parking
  labels:
    app: smart-parking-backend
  annotations:
    # AWS Load Balancer annotations (if using AWS)
    # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

    # GCP Load Balancer annotations (if using GCP)
    # cloud.google.com/load-balancer-type: "Internal"

    # Azure Load Balancer annotations (if using Azure)
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app: smart-parking-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: http

---
# Headless service for StatefulSet (if needed for MQTT connections)
apiVersion: v1
kind: Service
metadata:
  name: smart-parking-backend-headless
  namespace: smart-parking
  labels:
    app: smart-parking-backend
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: smart-parking-backend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
